packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^24.10.1
  typescript: ^5.9.3
  vitest: ^4.0.9
  wrangler: ^4.48.0
  xstate: ^5.24.0

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - sharp
  - workerd
